[package]
name = "chess-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
env_logger = "0.10.1"
log = "0.4.20"
